// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjkcwWEmXx0SBF-C3xw2-n4lz04DcQRc',
    appId: '1:377331470246:web:fe4a893e229ebe4fe00967',
    messagingSenderId: '377331470246',
    projectId: 'app-pokemon-aaf59',
    authDomain: 'app-pokemon-aaf59.firebaseapp.com',
    storageBucket: 'app-pokemon-aaf59.firebasestorage.app',
    measurementId: 'G-K3RHKNGGFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQcUFVEM2DSoDwPlhaFN4KfQSXmM51_lY',
    appId: '1:377331470246:android:d3fda069fc3efb2ee00967',
    messagingSenderId: '377331470246',
    projectId: 'app-pokemon-aaf59',
    storageBucket: 'app-pokemon-aaf59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfU9LqN1I3ktLil7r4KTTPybYrltD8xoc',
    appId: '1:377331470246:ios:d7a0b4e775fb4212e00967',
    messagingSenderId: '377331470246',
    projectId: 'app-pokemon-aaf59',
    storageBucket: 'app-pokemon-aaf59.firebasestorage.app',
    iosBundleId: 'com.example.pokerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfU9LqN1I3ktLil7r4KTTPybYrltD8xoc',
    appId: '1:377331470246:ios:d7a0b4e775fb4212e00967',
    messagingSenderId: '377331470246',
    projectId: 'app-pokemon-aaf59',
    storageBucket: 'app-pokemon-aaf59.firebasestorage.app',
    iosBundleId: 'com.example.pokerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHjkcwWEmXx0SBF-C3xw2-n4lz04DcQRc',
    appId: '1:377331470246:web:2fb3095d4f7ed57be00967',
    messagingSenderId: '377331470246',
    projectId: 'app-pokemon-aaf59',
    authDomain: 'app-pokemon-aaf59.firebaseapp.com',
    storageBucket: 'app-pokemon-aaf59.firebasestorage.app',
    measurementId: 'G-L367P7SGPJ',
  );
}
